name: "Documentation Commit"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  documentation:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]' && !contains(github.event.pull_request.title, '[skip ci]')

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Generate documentation
        run: |
          bundle exec yard doc

      - name: Check for documentation changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain doc/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit documentation updates
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'doc/'
          message: 'docs: update generated documentation [skip ci]'
          default_author: github_actions
          pathspec_error_handling: ignore
